### ISSUE TITLE
Test failure on alpha

### ISSUE THREAD

**Issue by LocutusOfBorg** [BLAKE2/libb2#10]
Hello, please note: alpha is not an official release architecture, so I don't care too much :)

```
make[3]: Leaving directory '/<<PKGBUILDDIR>>/src'
make  check-TESTS
make[3]: Entering directory '/<<PKGBUILDDIR>>/src'
make[4]: Entering directory '/<<PKGBUILDDIR>>/src'
PASS: blake2b-test
PASS: blake2s-test
FAIL: blake2sp-test
FAIL: blake2bp-test
====================================
   libb2 0.97: src/test-suite.log
====================================

# TOTAL: 4
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: blake2sp-test
===================

error
FAIL blake2sp-test (exit status: 255)

FAIL: blake2bp-test
===================

error
FAIL blake2bp-test (exit status: 255)

============================================================================
Testsuite summary for libb2 0.97
============================================================================
# TOTAL: 4
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to contact@blake2.net
```

**Comment by sneves** [comment]
OK, this one is harder to diagnose. Have you tried building with the `--disable-openmp` or `--enable-native` flag?

**Comment by LocutusOfBorg** [comment]
Unfortunately there aren't any public machines in Debian I can use to test, and I don't want to upload everywhere just to trace down this issue.
I prefer to close it if you think it is hard to debug, if one day Debian alpha becomes officially supported, we will have porterboxes to diagnose such issues (and maybe the test will pass because of toolchain fixes that day).
I suspect some toolchain issue to be honest

**Comment by LocutusOfBorg** [comment]
BTW I removed -march=native everywhere in Debian.

**Comment by sneves** [comment]
It does sound like some kind of toolchain issue. I'll close it, as I have no way of testing this either.
