### ISSUE TITLE
Missing 0.98 tarball

### ISSUE THREAD

**Issue by ilovezfs** [BLAKE2/libb2#15]
In Homebrew we're using https://blake2.net/libb2-0.97.tar.gz but it looks like the current version in the repository here is 0.98. Yet there is no https://blake2.net/libb2-0.98.tar.gz

**Comment by sneves** [comment]
I've added it to the Github [releases](https://github.com/BLAKE2/libb2/releases/tag/v0.98) page. Let us know if anything's broken.

**Comment by ThomasWaldmann** [comment]
close?
