### ISSUE TITLE
support pkg-config?

### ISSUE THREAD

**Issue by ThomasWaldmann** [BLAKE2/libb2#22]
it seems to be the standard way how to determine location of header/library files, library names, etc.:

https://en.wikipedia.org/wiki/Pkg-config

**Comment by ThomasWaldmann** [comment]
ping?

**Comment by sneves** [comment]
Pong. I'm not familiar with this `pkg-config` stuff, but I'd take a pull request with one.

**Comment by ThomasWaldmann** [comment]
I'm not familiar with it either.

It was just suggested in the borgbackup ticket (see link above) and I noticed all lib dependencies of borg support pkg-config, except libb2.

**Comment by RonnyPfannschmidt** [comment]
i just saw the comment on borg - i googled for a simple howto and it seems https://lists.freedesktop.org/archives/pkg-config/2007-August/000219.html does the trick, i will try to do it on the weekend but the toddler takes priority

**Comment by ThomasWaldmann** [comment]
thanks for doing a release with this!
